language: nix

os:
  - linux
  - osx

env:
  # some optional dependencies require higher versions and can't use older versions of them
  # - EMACS_CI=emacs-24-4
  # - EMACS_CI=emacs-24-5
  - EMACS_CI=emacs-25-3
  - EMACS_CI=emacs-26-3
  - EMACS_CI=emacs-snapshot

jobs:
  # mark finished as soon as required jobs complete
  fast_finish: true
  allow_failures:
    - env: EMACS_CI=emacs-snapshot
    - os: osx

before_install:
  - bash <(curl https://raw.githubusercontent.com/purcell/nix-emacs-ci/master/travis-install)
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install coreutils bash gnu-sed gawk grep gnu-getopt ; fi
  - make deps

script:
  - emacs --version
  - make test

after_success:
  # Upload coverage
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
